Fix cart pose jacobian calculation and unit test
mpowelson/trajopt_ros pull request #1
Opened 2019-09-09 23:33 UTC by Levi-Armstrong

2019-09-12 18:07 UTC, mpowelson requested changes
The only real change is that I think the coeffs need to be reversed for dynamicCartPose now. We also need to make sure we update the example in Tesseract.

2019-09-12 18:07 UTC, mpowelson commented on trajopt/src/kinematic_terms.cpp
> +  return calcTransformError(target_tf, link_tf);
If you do this, you will need to change the order of the coefficients on this one as well in problem description. You did this for cart pose but I don't think dynamic cart pose was done.

2019-09-12 18:07 UTC, mpowelson commented on trajopt/include/trajopt/utils.hpp
> +  theta = copysign(fmod(fabs(theta),2.0*M_PI), theta);
Some comments here would be nice. This gets it into +-2pi and below transforms it into +=pi

2019-09-12 18:07 UTC, mpowelson commented on trajopt/include/trajopt/utils.hpp
> + * @brief Calculate the rotation error given a rotation error matrix
Add to comment what the error is. ie the axis of the rotation * the magnitude.

2019-09-12 19:20 UTC, Levi-Armstrong commented on trajopt/include/trajopt/utils.hpp
> +  theta = copysign(fmod(fabs(theta),2.0*M_PI), theta);
I read the Eigen source code and they convert the rotation matrix to a quaternion then to angle axis and it states that the angle is between [0, PI] so I will remove this from the code.

2019-09-16 21:52 UTC, Levi-Armstrong commented
@mpowelson I have modified the jacobian calculation after reading the following [paper](https://ethz.ch/content/dam/ethz/special-interest/mavt/robotics-n-intelligent-systems/rsl-dam/documents/RobotDynamics2016/RD2016script.pdf). It looks like you can not use the kdl jacobian (Geometric Jacobian) directly. I tried the approach in the paper but need to revisit at another time. I have applied another approach to correctly get the partial derivative of the error function using the Geometric Jacobian. I will work on updating the DynamicCartPose.

2019-09-17 14:26 UTC, mpowelson commented
> @mpowelson I have modified the jacobian calculation after reading the following [paper](https://ethz.ch/content/dam/ethz/special-interest/mavt/robotics-n-intelligent-systems/rsl-dam/documents/RobotDynamics2016/RD2016script.pdf). It looks like you can not use the kdl jacobian (Geometric Jacobian) directly. I tried the approach in the paper but need to revisit at another time. I have applied another approach to correctly get the partial derivative of the error function using the Geometric Jacobian. I will work on updating the DynamicCartPose.

For posterity,  Sections 2.8.4 and 2.8.5 are the important ones here.

2019-09-17 15:46 UTC, mpowelson approved these changes

2019-09-17 15:46 UTC, merged